// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aijtzahdpvhovdrkolpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpanR6YWhkcHZob3ZkcmtvbHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzU1ODgsImV4cCI6MjA2ODI1MTU4OH0.n6lHWnXx5tCbxAU1fZ9PGU-k9da0qFMvAjdHICxF7HE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});